export * from './core/PermissionManager'
export * from './core/RouteGuard'
export * from './core/matchesPermissionCode'
// 会话读取口径也是公共面：守卫之外，各 app 判"当前会话能进哪个路由"要拿同一份权限码，
// 自己去 localStorage 解析信封就会重演"同一份权限，菜单看得见按钮点不动"
export * from './core/session'
export * from './guard'
export * from './directives/vPermission'
export * from './composables/usePermission'
